import type { ShopDef } from '@/types/content';
import { tableDefiner } from './define';

const defineShops = tableDefiner<ShopDef>();

const HOUR = 60 * 60 * 1000;

/** Fixed prices, finite stock that restocks over game time. Placed in zones by zones.ts. */
export const SHOPS = defineShops({
  hollow_goods: {
    name: 'Hollow Goods',
    description: 'The village general store. Buys almost anything at a bad price, sells the basics.',
    keeperId: 'keeper_pell',
    markup: 1.6,
    sellRate: 0.4,
    buys: 'all',
    restockMs: HOUR / 4,
    stock: [
      { itemId: 'shrimp', qty: 20 },
      { itemId: 'trout', qty: 5 },
      { itemId: 'oak_log', qty: 'infinite' },
      { itemId: 'rusty_dagger', qty: 'infinite' },
      { itemId: 'leather_gloves', qty: 3 },
      { itemId: 'wheat', qty: 20 },
    ],
  },
  sawmill: {
    name: "Hal's Sawmill",
    description: 'Logs and shields. Pays the best price for timber anywhere.',
    keeperId: 'woodsman_hal',
    markup: 1.5,
    sellRate: 0.6,
    buys: ['material'],
    restockMs: HOUR / 6,
    stock: [
      { itemId: 'oak_log', qty: 'infinite' },
      { itemId: 'willow_log', qty: 30 },
      { itemId: 'oak_shield', qty: 2 },
      { itemId: 'willow_shield', qty: 1 },
    ],
  },
  kingsport_armory: {
    name: 'Kingsport Armory',
    description: 'Weapons and armor up to steel. Buys arms at a fair rate.',
    keeperId: 'quartermaster_bex',
    markup: 1.7,
    sellRate: 0.5,
    buys: ['weapon', 'armor'],
    restockMs: HOUR / 2,
    stock: [
      { itemId: 'bronze_sword', qty: 3 },
      { itemId: 'bronze_axe', qty: 2 },
      { itemId: 'iron_sword', qty: 2 },
      { itemId: 'iron_dagger', qty: 2 },
      { itemId: 'iron_helmet', qty: 2 },
      { itemId: 'iron_platelegs', qty: 1 },
      { itemId: 'steel_sword', qty: 1 },
      { itemId: 'willow_shield', qty: 2 },
    ],
  },
  grand_bazaar: {
    name: 'Grand Bazaar',
    description: 'Materials from every road into the city. Buys anything at 45% of value.',
    keeperId: 'bazaar_master_ilse',
    markup: 1.6,
    sellRate: 0.45,
    buys: 'all',
    restockMs: HOUR / 4,
    stock: [
      { itemId: 'coal', qty: 10 },
      { itemId: 'iron_ore', qty: 20 },
      { itemId: 'cowhide', qty: 10 },
      { itemId: 'wolf_pelt', qty: 4 },
      { itemId: 'raw_trout', qty: 20 },
      { itemId: 'potato', qty: 20 },
      { itemId: 'sage', qty: 10 },
      { itemId: 'trout', qty: 10 },
    ],
  },
  curios: {
    name: "Marek's Curios",
    description: 'Trinkets for the two slots you have not filled yet.',
    keeperId: 'curio_dealer_marek',
    markup: 1,
    sellRate: 0.5,
    buys: ['armor'],
    restockMs: HOUR,
    stock: [
      { itemId: 'copper_ring', qty: 2, price: 150 },
      { itemId: 'amulet_of_vigor', qty: 1, price: 600 },
    ],
  },
  smithy: {
    name: "Orla's Smithy",
    description: 'Bars and bronze work beside the furnace. Orla buys back metal goods at a fair rate.',
    keeperId: 'smith_orla',
    markup: 1.8,
    sellRate: 0.5,
    buys: ['weapon', 'armor', 'material'],
    restockMs: HOUR / 2,
    stock: [
      { itemId: 'bronze_bar', qty: 10 },
      { itemId: 'bronze_dagger', qty: 3 },
      { itemId: 'bronze_helmet', qty: 2 },
      { itemId: 'iron_bar', qty: 4, price: 80 },
      { itemId: 'steel_bar', qty: 1, price: 220 },
    ],
  },
  prospectors_outpost: {
    name: "Dun's Outpost",
    description: 'A tent full of ore and optimism. The best price for raw ore this side of the woods.',
    keeperId: 'prospector_dun',
    markup: 1.5,
    sellRate: 0.6,
    buys: ['material'],
    restockMs: HOUR / 6,
    stock: [
      { itemId: 'copper_ore', qty: 30 },
      { itemId: 'tin_ore', qty: 30 },
      { itemId: 'iron_ore', qty: 8 },
      { itemId: 'coal', qty: 5 },
      { itemId: 'shrimp', qty: 10 },
    ],
  },
});
