import type { ZoneDef } from '@/types/content';
import { tableDefiner } from './define';

const defineZones = tableDefiner<ZoneDef>();

/** One zone per tier (two for tier 1). Zones from tier 2 up open when any skill reaches that tier. */
export const ZONES = defineZones({
  greenhollow: {
    name: 'Greenhollow Village',
    description: 'A quiet village with a furnace, a pond, an oak grove, a wheat field and a rat problem.',
    unlock: [],
    nodes: ['oak_tree', 'shrimp_spot', 'wheat_field', 'nettle_patch'],
    monsters: ['rat', 'cow'],
    npcs: ['elder_maren', 'captain_bram', 'smith_orla', 'angler_tobb', 'keeper_pell'],
    shops: ['hollow_goods', 'smithy'],
    traders: [],
    market: true,
  },
  copper_hills: {
    name: 'Copper Hills',
    description: 'Rolling hills east of the village. Copper and tin near the surface, goblins everywhere else.',
    unlock: [],
    nodes: ['copper_rock', 'tin_rock'],
    monsters: ['goblin'],
    npcs: ['prospector_dun'],
    shops: ['prospectors_outpost'],
    traders: ['peddler_vex'],
    market: false,
  },
  whispering_woods: {
    name: 'Whispering Woods',
    description: 'Willows, a fast river, potato patches gone wild, wolves, and people who would rather rob you than work.',
    unlock: [{ type: 'quest', questId: 'goblin_menace' }],
    nodes: ['willow_tree', 'trout_spot', 'potato_field', 'sage_patch'],
    monsters: ['wolf', 'bandit'],
    npcs: [],
    shops: [],
    traders: ['woods_hermit'],
    market: false,
  },
  old_iron_mines: {
    name: 'Old Iron Mines',
    description: 'Abandoned shafts full of iron, coal, spiders and the miners who never left.',
    unlock: [{ type: 'any_tier', tier: 2 }],
    nodes: ['iron_rock', 'coal_seam'],
    monsters: ['cave_spider', 'skeleton'],
    npcs: [],
    shops: [],
    traders: [],
    market: false,
  },
  blackfen_marsh: {
    name: 'Blackfen Marsh',
    description: 'Maples on stilts, salmon in black water, and things that are mostly mud.',
    unlock: [{ type: 'any_tier', tier: 3 }],
    nodes: ['maple_tree', 'salmon_spot', 'carrot_field', 'lavender_patch'],
    monsters: ['bear', 'bog_lurker'],
    npcs: [],
    shops: [],
    traders: [],
    market: false,
  },
  grey_peaks: {
    name: 'Grey Peaks',
    description: 'Mithril in the cliffs, yews on the ledges, terraced cabbage farms, and trolls who own all of it.',
    unlock: [{ type: 'any_tier', tier: 4 }],
    nodes: ['mithril_rock', 'yew_tree', 'tuna_spot', 'cabbage_field', 'bloodroot_patch'],
    monsters: ['troll', 'harpy'],
    npcs: [],
    shops: [],
    traders: [],
    market: false,
  },
  ashen_wastes: {
    name: 'Ashen Wastes',
    description: 'A burned land. Adamant under the cinders, ash trees that grow anyway, and a cult that likes it here.',
    unlock: [{ type: 'any_tier', tier: 5 }],
    nodes: ['adamant_rock', 'ash_tree', 'lobster_spot', 'pumpkin_field', 'moonflower_patch'],
    monsters: ['wyvern', 'cultist'],
    npcs: [],
    shops: [],
    traders: [],
    market: false,
  },
  dragons_reach: {
    name: "Dragon's Reach",
    description: 'Rune in the rock, elder trees older than the kingdom, and the two things that rule here.',
    unlock: [{ type: 'any_tier', tier: 6 }],
    nodes: ['rune_rock', 'elder_tree', 'swordfish_spot', 'sunfruit_field', 'dragonleaf_patch'],
    monsters: ['drake', 'lich'],
    npcs: [],
    shops: [],
    traders: [],
    market: false,
  },
});
